services:
  - type: web
    name: connect
    env: php
    region: oregon
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cqu9uraj1k6c73ds68ag-a
      - key: DB_DATABASE
        value: connect_90uv
      - key: DB_USERNAME
        value: connect
      - key: DB_PASSWORD
        value: zjTpPO9WdGhtlLbmtCpNYhCy8MomtMmE
    plan: standard
